---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - Launchpad
 - TV
 - Podcasts
 - 'App Store'
 - Maps
 - Photos
 - Freeform
 - Music
 - News
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - git-filter-repo
  - git-lfs
  - gh
  - glab
  - go
  - gpg
  - gnupg
  - age
  - httpie
  - htop
  - iperf
  - jq
  - libevent
  - mysql-client
  - nmap
  - node
  - nvm
  - openssl
  - php
  - postgresql@14
  - pre-commit
  - pv
  - pwgen
  - pyenv
  - readline
  - ssh-copy-id
  - sqlite
  - pngpaste
  - wget
  - wrk
  - yq
  - yt-dlp
  - zsh-history-substring-search

  # Essential CLI tools
  - tree
  - ripgrep
  - fd
  - tmux
  - dos2unix
  - rsync
  - thefuck
  - bat
  - eza
  - fzf
  - zoxide
  - git-delta
  - direnv
  - jless
  - tldr

  # Image processing
  - imagemagick

  # Network & diagnostics
  - mtr
  - iperf3
  - speedtest-cli

  # AWS/Cloud tools
  - awscli
  - aws-console
  - aws-iam-authenticator
  - aws-shell
  - aws/tap/aws-sam-cli
  - aws/tap/container-tools
  - aws/tap/k8s-tools
  - eksctl

  # Container/Kubernetes tools
  - docker-credential-helper-ecr
  - helm
  - kubernetes-cli

  # Infrastructure as Code
  - terraform
  - terraform-docs
  - tflint

  # Build tools
  - maven

  # Code quality & linting
  - shellcheck
  - yamllint
  - hadolint
  - actionlint

  # System
  - ca-certificates

homebrew_taps:
  # Note: homebrew/core and homebrew/cask are automatically tapped and deprecated as manual taps
  # Only keep taps that are actually needed for third-party repos or fonts
  - homebrew/cask-fonts
  - aws/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - cloudflare-warp
  - docker
  - google-chrome
  - handbrake
  - licecap
  - dbeaver-community
  - slack
  - sublime-text
  - vagrant
  - microsoft-office
  - session-manager-plugin
  - visual-studio-code
  - iterm2
  - temurin
  - postman
  - powershell
  - zoom-for-it-admins
  - vlc
  - microsoft-auto-update
  - adobe-acrobat-reader
  - microsoft-teams
  - stats
  - keepassxc
  - meld
  - google-drive
  - the-unarchiver
  - microsoft-remote-desktop
  - apache-directory-studio
  - backblaze
  - dash
  - rectangle
  - font-fira-code-nerd-font
  - font-jetbrains-mono-nerd-font

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
